# Generated by Django 5.1 on 2024-08-28 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
